name: Node CI

on: [push]

jobs:
  chromatic:
    if: github.actor != 'kevinbarabash'
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v1
      - name: Echo actor
        run: echo ${{github.actor}}
      - name: Echo ref
        run: echo ${{github.ref}}
      # - name: Use Node.js 12.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 12.x
      # - name: Get yarn cache
      #   id: yarn-cache
      #   run: echo "::set-output name=dir::$(yarn cache dir)"
      # - uses: actions/cache@v1
      #   with:
      #     path: ${{ steps.yarn-cache.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      # - name: Cache node modules
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-node_modules-
      # - name: yarn install
      #   run: yarn install
      # - uses: chromaui/action@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     appCode: ${{ secrets.CHROMATIC_APP_CODE }}
      #     autoAcceptChanges: "master"
